name: Scrape Data and Save to CSV

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("rvest", "tibble", "dplyr", "readr"))'

      - name: Run scraper script
        run: |
          Rscript scrape_data.R

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add scrape_data.csv
          git commit -m "Update scraped data [auto]" || echo "No changes to commit"
          git push
