name: Scrape Website and Save CSV

on:
  workflow_dispatch:
  push:
    paths:
      - "scrape-data.R"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rvest", "tidyverse", "lubridate"))'

      - name: Run scraper
        run: Rscript scrape-data.R

      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: output/*.csv
